[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$DumpReference,

    [Parameter(Mandatory = $true)]
    [string]$FileName,

    [string]$PackageName = "com.layeranalyzer.android",

    [string]$OutputDirectory = (Join-Path (Get-Location) "agent_response_dump_export")
)

$ErrorActionPreference = "Stop"
$expectedPackage = "com.layeranalyzer.android"
if ($PackageName -ne $expectedPackage) {
    throw "Refusing package '$PackageName'. Export is limited to $expectedPackage."
}

# The reference is generated by AgentResponseDebugCapture and is deliberately
# path-free. Do not accept a device path, a separator, or an arbitrary name.
if ($DumpReference -notmatch '^[0-9a-f]{12}-[0-9a-f]+-[0-9]{10,20}$') {
    throw "Invalid dump reference."
}
if ([System.IO.Path]::IsPathRooted($FileName) -or
    $FileName.Contains('/') -or $FileName.Contains('\') -or
    $FileName.Contains('..') -or
    $FileName -notmatch ('^dump-' + [regex]::Escape($DumpReference) + '\.(json(?:\.part)?|sse(?:\.part)?|metadata\.json|summary\.json)$')) {
    throw "FileName must name one file belonging to the supplied dump reference."
}

$deviceRelative = "no_backup/agent_response_dumps/$FileName"
$deviceCheck = & adb shell run-as $PackageName test -f $deviceRelative 2>&1
if ($LASTEXITCODE -ne 0) {
    throw "Dump file was not found in the private response-dump directory."
}

$destinationRoot = [System.IO.Path]::GetFullPath($OutputDirectory)
New-Item -ItemType Directory -Force -Path $destinationRoot | Out-Null
$destination = [System.IO.Path]::GetFullPath((Join-Path $destinationRoot $FileName))
if (-not $destination.StartsWith($destinationRoot + [System.IO.Path]::DirectorySeparatorChar, [StringComparison]::OrdinalIgnoreCase)) {
    throw "Destination escapes the export directory."
}

# adb exec-out emits only the selected private file; no directory or device
# path supplied by the caller is ever interpolated into the command.
& adb exec-out run-as $PackageName cat $deviceRelative > $destination
if ($LASTEXITCODE -ne 0) {
    Remove-Item -LiteralPath $destination -Force -ErrorAction SilentlyContinue
    throw "adb failed while exporting the selected dump file."
}

Write-Output "Exported one dump file to $destination"
